version: '2'

services:
  egdn-mssql:
    image: microsoft/mssql-server-linux:2017-latest
    hostname: egdn-mssql
    ports:
      - "1433:1433"
    networks:
      egdn:
        aliases:
          - egdn-mssql
    environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=P@ssword2

  identity-api:
    image: ramysihacofo/identity-api
    hostname: egdn-identity
    environment:
      - ASPNETCORE_URLS=http://+:9090
      - ASPNETCORE_ENVIRONMENT=local
    ports:
      - "9090:9090"
    networks:
      egdn:
        aliases:
          - egdn-identity
    build:
      context: src/Services/Identity/
      dockerfile: Dockerfile 
    depends_on:
      - egdn-mssql

  policy-api:
    image: ramysihacofo/policy-api
    hostname: egdn-policy
    ports:
      - "8080:8080"
    networks:
      egdn:
        aliases:
          - egdn-policy
    build:
      context: src/
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=local
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - egdn-mssql

  apigw:
    image: ramysihacofo/apigw
    ports:
            - "80:80"
    hostname: egdn-gw
    networks:
      egdn:
        aliases:
          - egdn-gw
    environment:
      - ASPNETCORE_ENVIRONMENT=local
      - ASPNETCORE_URLS=http://+:80
    build:
      context: src/Gateway/Gateway.WebApi/
      dockerfile: Dockerfile
    depends_on:
      - egdn-mssql
      - identity-api
      - policy-api

networks:
  egdn:
    driver: bridge        
